### ISSUE TITLE
Document the Infrastructure for the service

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/whatsapp-webhook-analytics#11]
**Is your feature request related to a problem? Please describe.**
We have developed the WhatsApp-webhook-analytics service. We wanted to document the overall infrastructure for better understanding for someone who is not aware of it.

**Describe the solution you'd like**
- [x] Documentation of the overall infrastructure for the service.
- [x] Share the doc with the team.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Acceptance Criteria**
- [x] The documentation should be linked to the Issue comment and Notion as well.

**Documentation**
Add whatever documentation will be required here.

**Comment by kritirakheja** [comment]
@Satendra-SR are we picking this in this quarter? If not let's move this to Q3

**Comment by Satendra-SR** [comment]
@kritirakheja it was targeted as a part of webhook service completion - and picked in this sprint.

This is completed

**Comment by Satendra-SR** [comment]
Here is the service documentation, which includes:
1. Tech stack
2. Infrastructure
3. Database schema
4. Other relevant details

https://www.notion.so/dosteducation/Whatsapp-webhook-service-21d08fb6c62e46e19ebc5bbb9068e8e0?pvs=4

Closing this now
