### ISSUE TITLE
[FEATURE] Create a user flow run logs service.

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/whatsapp-webhook-analytics#15]
**Is your feature request related to a problem? Please describe.**
We need a service to store the flow run details in the database whenever will get webhooks from the Glific flows for any user we want to hold that record in the database.

**Describe the solution you'd like**
- [x] Handle webhook to get details like:
  - [x] user phone
  - [x] flow uuid
  - [x] flow name
  - [x] flow type
  - [x] flow run status
  - [x] flow start time
  - [x] flow end time
  - [x] flow is active or not
- [x] Add logic to create a new entry in the user flow table.
- [x] Logic to update the details in the same entry once the flow ends.
- [x] Add a check to verify if the user flow details are already in the database.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Acceptance Criteria**
- [x] The flow run details should be added or updated in the table properly for the users.

**Documentation**
Add whatever documentation will be required here.

**Comment by kritirakheja** [comment]
@Satendra-SR are we picking this in this quarter? If not let's move this to Q3

**Comment by Satendra-SR** [comment]
This is being a part of Glific integration @kritirakheja and already being worked on

**Comment by Sachinbisht27** [comment]
### Details on the items that are done in the story:

- Handled the webhook to capture the required details for the feature.
- Added logic to create new logs in the user-flow table based on several conditions.
- Logic to update the new details in the same entry till the flow ends.
- Added logic to verify if the user flow details are already in the database.
- Testing of the functionality locally and on the staging environment.

**Out of scope work:**
- The indexing of a few columns in the existing tables as it going to take more resources as the table grows.
- Generating migration for the indexing of the columns in the tables.
- Test all the functionalities that may be relatable. 

**Issue comment:**
https://github.com/DostEducation/whatsapp-webhook-analytics/pull/24#discussion_r1587719943

Screenshots:
![image](https://github.com/DostEducation/whatsapp-webhook-analytics/assets/96137915/db6b05e9-86ae-4347-963f-ea866811a9a4)
