### ISSUE TITLE
[FEATURE] Create a user activities service.

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/whatsapp-webhook-analytics#17]
**Is your feature request related to a problem? Please describe.**
We need a service to track the user activity details for every flow as we wanted to know the engagement of the user while listening to the flow. We need to store the user activity details in the database as the flow proceeds for the user.

**Describe the solution you'd like**
- [x] Handle webhook to get details like:
  - [x] The activity name
  - [x] started or not?
  - [x] started on time
  - [x] succeeded or not?
  - [x] succeeded on time
  - [x] completed or not?
  - [x] completed on time
- [x] Logic to create a new entry for the new flow run details.
- [x] Logic to update the record in the same entry if a flow started for the user.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Acceptance Criteria**
- [x] The user activities for the flow should be recorded properly in the database.

**Documentation**
Add whatever documentation will be required here.

**Comment by kritirakheja** [comment]
@Satendra-SR are we picking this in this quarter? If not let's move this to Q3

**Comment by Satendra-SR** [comment]
Yes @kritirakheja 
This is already being picked

**Comment by Sachinbisht27** [comment]
Closing the issue as completed and released on production.
