### ISSUE TITLE
[FEATURE] Create a user attribute service.

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/whatsapp-webhook-analytics#18]
**Is your feature request related to a problem? Please describe.**
We wanted to store the user's custom field details on our database. The details should be updated once these are changed by the user in the Gilfic contact. 

**Describe the solution you'd like**
- [x] Handle all custom field data from the Glific webhook.
- [x] Create a new entry for every new custom field.
- [x] Add logic to update the same entry again once the user changes or updates the details.
- [x] Add check not to create multiple entries for the same contact field for a user.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Acceptance Criteria**
- [x] The user costume field and the field values details should be updated properly on the user attribute table.

**Documentation**
Add whatever documentation will be required here.

**Comment by kritirakheja** [comment]
@Satendra-SR are we picking this in this quarter? If not let's move this to Q3

**Comment by Sachinbisht27** [comment]
Closing as completed
