### ISSUE TITLE
[Onboarding Data source] Setup development environment on DBT cloud 

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/whatsapp-webhook-analytics#28]
**Parent issue - https://github.com/DostEducation/whatsapp-webhook-analytics/issues/25**

**Is your feature request related to a problem? Please describe.**
We need to set up the DBT project for the webhook service which will be responsible for transforming the data stored at the BigQuery level. Therefore we wanted to set up the DBT project for development.

There are two ways to achieve it - 
1. Setting up the DBT core on our local machine and using it
2. Setting up the DBT cloud and configuring WhatsApp analytics GitHub repo for development. 

As the Cloud is quick to set and easy to use, let's go with the DBT cloud - it gives one project setup free per GitHub user.

**Describe the solution you'd like**
- [x] Create a basic understanding of the DBT tool 
    - DBT core
    - DBT cloud.
- [x] Check out GitHub and Notion docs - DBT cloud Setup guidelines - [Link to the Notion document](https://www.notion.so/dosteducation/DBT-Cloud-setup-c959c8b4893a497b9966fee91de1a562?pvs=4)
- [x] Setup with your email 
    - [x] Create a new DBT cloud account and configure it
    - [x] Steup connection with BigQuery - Reach out to @Satendra-SR for service account JSON credentials
    - [x] Setup connection with Github repository
- [x] Test run the project.

**Describe alternatives you've considered**
NA

**Additional context**
- GitHub for the DBT Cloud for WhatsApp analytics - https://github.com/DostEducation/dbt-whatsapp-analytics

**Acceptance Criteria**
- [x] The DBT cloud should be configured and ready to be used for development.
- [x] You should be able to test-run the project.

**Documentation**
Add whatever documentation will be required here.

**Comment by Sachinbisht27** [comment]
Closing as completed.

**Comment by Satendra-SR** [comment]
Tracking of Errors while running `dbt run`

1. https://github.com/DostEducation/dbt-whatsapp-analytics/issues/48
2. https://github.com/DostEducation/dbt-whatsapp-analytics/issues/47
