### ISSUE TITLE
[BUG] Correct datatype for timestamp columns in all tables

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/whatsapp-webhook-analytics#37]
**Describe the bug**
While migrating the data from the application database to BigQuery, we faced an issue: The Datetime column's data was not getting migrated because it supports the timestamp with timezone only. We wanted to correct all the timestamp columns in the application to the timestamptz.

**To Reproduce**
Run Migrations on AirByte.

**Expected behavior**
- [x] All the timestamp columns in the application models should be updated to timestamptz.
  - [x] Update the logic to pick a time in IST only.
  - [x] Correct all models to enable the timezone.
  - [x] Create migrations for all the changes in the model schema.
  - [x] Test and deploy.

**Additional context**
NA

**Acceptance Criteria**
- [x] The migrations in the AirByte should run properly without any issues.

**Documentation**
Add whatever documentation will be required here.

**Comment by Sachinbisht27** [comment]
Closing the issue as completed and released on production.

**Comment by Satendra-SR** [comment]
Parent issue - https://github.com/DostEducation/whatsapp-webhook-analytics/issues/40
