### ISSUE TITLE
[BugFix] Correct the logic of user flow and activities to handle webhooks

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/whatsapp-webhook-analytics#47]
**Describe the bug**
We need to correct the logic for the user flow and user activities. Also, we need to fix the naming convention for the different contact fields and values.

**Expected behavior**
- [x] Update the FlowRunStatus STARTED to SENT.
- [x] Correct the logic to check whether the value of the contact field is yes or not.
- [x] Add a check to confirm the flow_type is None or not if None then use default type activity.

**Additional context**
NA

**Acceptance Criteria**
- [x] The functionality for creating and updating the user flow and activities should work fine.

**Documentation**
Add whatever documentation will be required here.

**Comment by Sachinbisht27** [comment]
Closing as completed

**Comment by Satendra-SR** [comment]
### Additional efforts breakdown:

The following changes are done as a part of the changes we have targeted in this item - [Link to PR ](https://github.com/DostEducation/whatsapp-webhook-analytics/pull/46) https://github.com/DostEducation/whatsapp-webhook-analytics/pull/46


1. **Cleaned up SQLALCHEMY_ECHO configuration -** 
    - Initially, debugging the database required a configuration variable to pinpoint the root cause.
    - Over time, this variable generated excessive logs in production, so we removed this config variable.
    - Following the cleanup, we thoroughly tested the system's database interactions.

<img width="1078" alt="image" src="https://github.com/DostEducation/whatsapp-webhook-analytics/assets/39792899/ef54ee5a-13b3-410c-ade4-863242b47b63">

2. **Made some cleanup for better logging**
<img width="811" alt="image" src="https://github.com/DostEducation/whatsapp-webhook-analytics/assets/39792899/e1cbb31b-2fd2-45c9-8cd0-c8bbd455f58f">
