### ISSUE TITLE
Cloud function for Staging

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/whatsapp-webhook-analytics#7]
**Is your feature request related to a problem? Please describe.**
We need a cloud function for the webhook requests handling and processing coming from Glific. 

**Describe the solution you'd like**
- [x] Setup Gen 2 Cloud-Function
- [x] Connect it with a CloudSQL instance
- [x] Deploy a sample application to check things running fine.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Acceptance Criteria**
- [x] The cloud function should work fine for accepting requests from glific.

**Documentation**
Add whatever documentation will be required here.

**Comment by Sachinbisht27** [comment]
Closing as completed
