### ISSUE TITLE
Database setup for staging and Production

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/whatsapp-webhook-analytics#9]
**Is your feature request related to a problem? Please describe.**
We have developed the WhatsApp-webhook-analytics service. We need databases for both staging and production of the environments.

**Describe the solution you'd like**
- [x] Create a database in the `rp_ivr-staging` CloudSQL instance. - For Staging WhatsApp-webhook-analytics - [The load on this instance is very low.]
- [x] Create a database in the `rp_ivr-prod` CloudSQL instance - For Production WhatsApp-webhook-analytics - [Will first utilize the same instance until pilot.]

**Describe alternatives you've considered**
Let's use the staging and production database instances for now to avoid any additional cost for the pilot, we will move it to a separate database server once we have more load.

**Additional context**
NA

**Acceptance Criteria**
- [x] Service in both of the environments should be connected with the Databases properly.

**Documentation**
Add whatever documentation will be required here.

**Comment by Sachinbisht27** [comment]
Closing as completed
